### ISSUE TITLE
Need to review the license

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#11]
GPLv3 seems to be not always accepted. There might be an issue as derived code must be placed under the GPL, question is if derived code such as generated code falls also under the GPL. In genera is should be fine to use a more permissive licenses. Need to research which one fits best.

**Comment by jeremiah** [comment]
You can choose whatever license you think best. But I'm not certain that derived code would in fact be under the GPL. As its been explained to me, the GPLv3 bits have to travel, that is to say that any code under GPLv3 has to be part of the new code as the tool transforms the code to an interface. And, even it if is the case, you can easily provide an exception to allow people to use the derived code under a different license. But from what I understand, you're only crafting interfaces, so you should not be having any affect on anyone else's code.

Alternatively, if GPLv3 is not to your liking (it is a very good and flexible license IMHO,) you can use GPLv2 which would clarify any questions about anti-tivoization which I assume is the ultimate issue. 

Lastly, if you decided to use MPL, Apache or any of the other permissive licenses, you have to be prepared for people to take the code and not return any changes back. If that is okay with you, my recommendation would be to use the Mozilla Public License 2.0 which is a very good license, much better than the MIT in this case.

**Comment by jryannel** [comment]
We need to ensure that customer clearly understand that generated code can be under any license and we do not restrict them. So they are free to create an own generator and have their generated code under any license they choose.

**Comment by jryannel** [comment]
We should probably opt for using the MPL 2.0 as suggested by Jeremiah. Forking the project is not so much an issue. The IDL format is the binding layer.

**Comment by jryannel** [comment]
The license has been updated to the MIT license to open up the use of QFace library in other projects.

**Comment by jeremiah** [comment]
I think that MIT license is a poor choice. It doesn't protect against patent claims for example. If you want a permissive license, I still think that the Mozilla Public License 2.0 is the best choice.

**Comment by jryannel** [comment]
Okay. I will discuss these with the other participants. Thanks for letting me know.
