### ISSUE TITLE
Add CMake support for qtcpp generator

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#17]
The qtcpp generator should also create a CMakeLists file to support the CMake build tool

**Comment by jryannel** [comment]
Someone which knowledge of CMake would need to help here and create a pull request.

**Comment by GordanM** [comment]
Hey Jürgen, I'd be happy to help. Hopefully I will find some time soon to do this.

**Comment by jryannel** [comment]
@GordanM would be awesome. Thx. I will also try to enable a colleague of mine.
