### ISSUE TITLE
Allow an interface to extend another interface

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#32]
- It shall be possible to inherit only from one interface
- An interface from another module need to be specified by the FQN
- Extending an interface shall be part of the extended IDL profile
```js
interface Climate {
}

interface ClimateV2 extends Climate {
  int customTemperature;
}
```

**Comment by jacky309** [comment]
Any hope to see that feature implemented soon ?

**Comment by jryannel** [comment]
Sure

**Comment by jryannel** [comment]
Seems it ws already in since April: 5259ad681af61d497419def84752582f5503d8cd

**Comment by jryannel** [comment]
You can write now an interface using the extends syntax. The symbol is available under `interface.extends` which will return the symbol object
