### ISSUE TITLE
Properties of "interface" type

### ISSUE THREAD

**Issue by jacky309** [Pelagicore/qface#48]
It seems like it is already possible to have a property of interface type. Example:

interface SubInterface {
    void doSomething();
}

interface MainInterface {
    readonly SubInterface myProperty;
}

However, I could not find out how a code generator can check whether a property is of interface type or not. I would expect that an additional "is_interface" field is added, so that we could write the following:

    {% if property.type.is_model -%}   // "is_model" field already existing
   // the property is a model
    {% elif property.type.is_interface -%}  // "is_interface" field not existing yet
   // the property is a sub interface
    {% endif %}

**Comment by jacky309** [comment]
Fixed by https://github.com/Pelagicore/qface/pull/49

**Comment by jryannel** [comment]
Seems to be okay. Done. I added some tests to validate the expectation
