### ISSUE TITLE
History is messy due to merge commits

### ISSUE THREAD

**Issue by jacky309** [Pelagicore/qface#50]
Merge commits cause the history to be messy.
I think the repository should be configured in such a way that a rebase is performed when merging a pull request.

**Comment by jryannel** [comment]
Not sure how to change these settings in github. Will try the next time

**Comment by GordanM** [comment]
@jryannel select settings on the top menu of your repository and there will be a selection list regarding PRs under the "Merge button" heading:

* Allow merge commits
* Allow squash merging
* Allow rebase merging

The merge commits can be explicitly turned off to prevent further situations like this.

**Comment by jryannel** [comment]
The merge commits are turned off

**Comment by jryannel** [comment]
Maybe it was because I manually merged the commit and then pushed it. Instead of using github. I wanted to make changes on Jacques pull request but was not able todo so it seems.

**Comment by jryannel** [comment]
Checked
