### ISSUE TITLE
Identifying flags for property declarations

### ISSUE THREAD

**Issue by mkrus** [Pelagicore/qface#55]
I'm trying to modify my generator to properly support Q_DECLARE_FLAGS and Q_FLAGS

When iterating on the enums in the template, 'for enum in module.enums', enum.is_flag is true, all good. I'm just adding 's' to the enum type name in my Q_DECLARE_FLAGS call.

However, I need to replace the parameter_type and return_type filters to also add the 's'. In that case, I need to determine if the enum is a flag. 'symbol.type.is_enum' is true, but how do I get the actual type instance to find out if Enum.is_flag is true?

**Comment by mkrus** [comment]
actually 'symbol.type.reference.is_flag' is what I'm looking for.  Not sure there should be a better way to handle flags in a Qt way without having to override the helper implementations

**Comment by jryannel** [comment]
The symbol type is of type TypeSymbol and the reference doe resolve the original type of type Symbol. Which in your case is the enum you referring to. 

When I look at my current examples, it seems I never generated the flag use case, just the enums currently. So this is missing.

For the 's' naming. I assume this is for pluralisation case. Not every word is pluralized that way in .proper english. So I would assume a pluralize jinja filter could do the job. But for what I understand your require the words (singular/plural) need to be different. Which is in an correct pluralization solution not given. So you better of just appending 's' or a different full word.

**Comment by mkrus** [comment]
indeed, it's an imperfect solution. jinja pluralisation is possible except I also need to be able to get that from my python filter to build proper type names.

For the time being I'm going to add an annotation to let the user specify the "plural" manually at declaration time.
