### ISSUE TITLE
The @brief tag should support multiple lines

### ISSUE THREAD

**Issue by Gagi2k** [Pelagicore/qface#57]
Currently the @brief tag only supports one line.

For comments like the following this leads to a problem:

`/**
  * @brief Holds the steering wheel heater level, where the level can
  * be between minimumValue(off) to maximumValue (warmest).
  */`

Currently only the last line is in the brief property and the rest is lost

**Comment by jryannel** [comment]
See 42e54ed4d4f5baf7f4c63b9b6640120b6d6ff92c
