### ISSUE TITLE
Add parser error handling

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#59]
Be able to nicely format any parser errors to the console while parsing.

**Comment by jryannel** [comment]
Started to add initial handling of parser errors. The grammar limits our ability to error detection.

**Comment by vifactor** [comment]
Incorrect annotation syntax does not produce errors or warnings.
The following interface
```
@tag
interface Echo {
    readonly Message lastMessage;
    void echo(Message message);
    signal callMe();
};
```
using
```python
for interface in module.interfaces:
    for tag in interface.tags:
        print(tag) 
```
will print three symbols: t, a, g
