### ISSUE TITLE
add possibility to define own types

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#6]
It could be possible to add your own typedef with additional decorations.

```js
@range(min=0, max=40)
@unit("degree")
@constants(Off: 0, Full: 40)
@comment(text="0 is the min value in degrees. Annd 40 is the maximum value")
typedef int FanSpeedLevel 
```

The decorations couldbe added to a helper object for the typedef. Maybe like this

```cpp
class FanspeedLevelType {
    enum SpecialValues {
        Off = 0,
        Full = 40
        Min = 0
        Max = 40
    }
    int clip(int value);
    bool isValid(int value);
    bool isOff(int value);
}
```

**Comment by jryannel** [comment]
If at all, this might be part of a later release. Do not see yet the benefits.

**Comment by jryannel** [comment]
Will be closed by now. Own type definition will not be supported until we see a real need here.

**Comment by derived-coder** [comment]
I would like to use an already existing class, independent of QFace, which is already exposed to QML.
This type I want to use inside a QFace definition. This would be quite handy for me.

My use case is, I have a library which is used for units in C++ has also all the unit conversion algorithms on board. I would like to use this types inside my QFace generated interfaces.
