### ISSUE TITLE
Support of Qt style doxygen/qdoc comments

### ISSUE THREAD

**Issue by jacky309** [Pelagicore/qface#65]
The parser currently only recognizes javadoc style comment (/** .... */) . It would make sense to also recognize Qt style (/*! ... */), given the relationship between QFace and Qt.

**Comment by jryannel** [comment]
It is intentional to only support only one syntax. I would argue this makes the use and documentation much easier.

Hope this is okay with you.

**Comment by jryannel** [comment]
I will close this, as there seems to be no response.
