### ISSUE TITLE
Comment information provided as raw text

### ISSUE THREAD

**Issue by jacky309** [Pelagicore/qface#66]
In order to enable operations on the comments during code generation (such as adding content or producing either qdoc or javadoc comments style), it would be convenient that the domain model  provides comment information without the enclosing "/** */" (or "/*! */").

**Comment by jryannel** [comment]
You need to use the parse_doc filter in qface.helper.doc and add these template code
```js
{% with doc = property.comment|parse_doc %}
   \brief {{doc.brief}}

   {{doc.description}}
{% endwith %}
```

The parse doc removes the enclosing tags and provides you a structured content. See 

* qface/helper/doc.py
* qface/templates/qface/qtcpp.j2

Maybe the documentation is not clear on this.

**Comment by jryannel** [comment]
This is document in the extension chapter: http://qface.readthedocs.io/en/latest/extending.html#parsing-documentation-comments
