### ISSUE TITLE
Support for maps

### ISSUE THREAD

**Issue by jacky309** [Pelagicore/qface#69]
I believe maps should be supported by QFace. The documentation mentions the following: "The reason for not providing a map container type is that keys in dictionaries requires a hash which can not always be guaranteed to be available in complex types."
IMO, it should not be up to QFace (which is only an IDL) to dictate a limitation which is relevant to the generated code only. It is up to the code generator to generate hash functions if they are needed.

**Comment by jryannel** [comment]
I agree it should support it somehow. Still I would like to make it optional for the generators to support it. I just need to get the qface profiles in so that I can can create a profile (e.g. basic) which would not support maps.

This may take a short time. Contributions are welcome.

**Comment by jryannel** [comment]
Initially we could support a simple map type, which only stated the value type.

```
map<Station> stationMap
```

And leave it to the generator to define the exact key. Recommendation is to use a string type as the key. This would in generally work for Qt when used with a QVariantMap. In scripting languages this should also be fine.

In a 2nd step we then can add an optional key type

```
map<int,Station> stationMap
```

**Comment by jryannel** [comment]
QFace 1.10 adds support for maps as a keyword, but it only supports the value type.

```
map<Station> stations;
```

The key should be generically defined by the generator. A (optional) key-type might be added in the future.
