### ISSUE TITLE
convert scripts to use python2 as this is default on most linux distros today

### ISSUE THREAD

**Issue by jryannel** [Pelagicore/qface#8]

**Comment by DunderRoffe** [comment]
I would go for Python3 compatible Python2 code. Then both systems using Python 2 and Python 3 can use it.

**Comment by rpannek** [comment]
It's still a easy first step/fix to do that.

**Comment by jryannel** [comment]
Means I need to add tests using python2 code. But then I would loose the type annotations I use everywhere. Need to evaluate this.

Also I figured out all distress seem to have Python3 installed, so Py3 seems not a big issue.

**Comment by jryannel** [comment]
Python3 is sufficient and seems to be okay with most people.

**Comment by mkrus** [comment]
Python2 is the default on macOS

**Comment by jryannel** [comment]
There seems to be issues with the python antlr4 runtime. It exists either as a python2 module or python3 module. The python2 module is not compatible for python3. So I would currently recommend not to continue this road.

**Comment by mkrus** [comment]
i don't quite get what the issue is? you can't install both? But it you only have either 2 or 3 you should be fine?

**Comment by jryannel** [comment]
ANTLR also generates the parser code in python. This code differs between 2 and 2. A python3 generated code will not work with python2 runtime, vice versa. 

Sorry I should have been more exact.

**Comment by mkrus** [comment]
could the generation of the parser by done when qface is installed? rather than shipping it?
or have two versions?
I'm not against having python3 as a requirement, just exploring the options

**Comment by jryannel** [comment]
Maybe it would be possible when installing the package. But it makes it impractical for people using the git clone. You would need to run a generator command to initialise the repository. Testing/validation would also be more complicated.

I think the effort and the benefits are not really balanced here.

**Comment by mkrus** [comment]
maybe the generator could build the parser on first invocation? or if the grammar changes?

I'm just worried we are putting a burden on all the future users of qface who don't have python3. But I guess it's fine, it is a one time thing to install it

**Comment by jryannel** [comment]
Python 2.7 is the last release of Python2 and Python2 will have end of live in 2020 (see https://www.python.org/dev/peps/pep-0373/#id2). I'm really resistant to make the code so much more complicated. The maintenance overhead on our side needs to stay low.

I will expect that people which know how to install python packages know how to install python. And all the others will anyway have someone who distributed the packages as part of their generator. They can use http://www.pyinstaller.org to create a binary package for their generator.

**Comment by mkrus** [comment]
ok, fine with me

**Comment by jryannel** [comment]
Another issue came up with generating the parser code on the fly. For this we would need to have ANTLR installed which is a JAVA tool. This would add a new dimension of dependency.
